### PR TITLE
Skip gem trace lines by ignoring file paths starting with /b.

### PR DESCRIPTION
**Pull request by nroose**

### CODE REVIEW

**Comment by cmaujean** [comment]
I feel like this should be configurable. As a non-RP user of this library, I might want to get gem paths in my traces.

**Comment by cmaujean** [comment]
Also, I have #{Rails.root}/bin in a project, and do some audits from /bin. Is there a more specific test that this could use to detect gem traces?

**Comment by nroose** [comment]
@cmaujean Seems like giving up the stack trace lines in /bin is ok as a compromise. Making it configurable and making it include /bin both make it more complex.
If you can't live with this, can you skip this version and work on a change after this that you can live with?

**Comment by cmaujean** [comment]
@nroose sounds good.

**Pull request merged**
